---
- name: Install OS Packages
  hosts: localhost
  vars:
  pre_tasks:
    - block:
        - name: Ensuring Homebrew Is Installed
          stat:
            path: "/usr/local/bin/brew"
          register: "homebrew_check"

        - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
          fail:
            msg: "Homebrew is missing...Install from http://brew.sh/"
          when: >
                not homebrew_check.stat.exists and
                not install_homebrew_if_missing

        - name: Installing Homebrew
          command: >
                   /usr/bin/ruby -e \
                   "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          when: >
                not homebrew_check.stat.exists and
                install_homebrew_if_missing
      when: ansible_os_family == "Darwin"

  tasks:
    - block:

        - name: Updating Homebrew
          homebrew:
            update_homebrew: true
          when: homebrew_check.stat.exists

        - name: Installing Homebrew Packages
          homebrew:
            name: "{{ item }}"
            state: "present"
            upgrade_all: "{{ upgrade_homebrew_packages }}"
          with_items: '{{ brew_packages }}'
          when: homebrew_check.stat.exists

        - name: Installing Homebrew Cask Packages
          homebrew_cask:
            name: "{{ item }}"
            state: "present"
          with_items: '{{ brew_cask_packages }}'
          when: homebrew_check.stat.exists

      when: ansible_os_family == "Darwin"

    - block:

        - name: Updating Apt Cache
          apt:
            update_cache: true
            cache_valid_time: 3600
          become: true

        - name: Installing OS Packages
          apt:
            name: "{{ item }}"
            state: "present"
          become: true
          with_items: '{{ debian_packages }}'

      when: ansible_os_family == "Debian"

    - block:

      - name: Installing OS Packages
        yum:
          name: "{{ item }}"
          state: "present"
        become: true
        with_items: '{{ redhat_packages }}'

      when: >
            ansible_os_family == "RedHat" and
            ansible_distribution != "Fedora"

    - block:

      - name: Installing OS Packages
        dnf:
          name: "{{ item }}"
          state: "present"
        become: true
        with_items: '{{ redhat_packages }}'

      when: >
            ansible_os_family == "RedHat" and
            ansible_distribution == "Fedora"

    # - name: Installing Python Modules
    #   pip:
    #     name: "{{ item }}"
    #     state: "present"
    #   with_items: '{{ python_modules }}'
