---
- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install Homebrew Packages
      homebrew:
        name:
          - asciinema
          - bat
          - gh
          - git
          - git-crypt
          - git-lfs
          - kind
          - kubernetes-cli
          - kubernetes-helm
          - rclone
          - tfenv
        state: present
